### ISSUE TITLE
Little bugs in the german language files

### ISSUE THREAD

**Issue by Dante1975X** [OpenVoiceOS/skill-ovos-wikipedia#26]
When booting ovos. There are two error messages from the wikipedia skill:

```
Failed to parse the line "wörterbuch {query)" for skill-ovos-wikipedia.openvoiceos:wiki.intent
Failed to parse the line "wiki {query)" for skill-ovos-wikipedia.openvoiceos:wiki.intent
```
The bug seems to be in https://github.com/OpenVoiceOS/skill-ovos-wikipedia/blob/dev/locale/de-de/wiki.intent. In both cases there is a ")" instead of "}".

**Comment by goldyfruit** [comment]
Image has been rebuilt.

**Comment by Dante1975X** [comment]
Thanks for the update of the German wiki.intent file. It looks fine now.

But: The wiki.intent is still not working for me. Neither in German nor in English. I think the intent is recognized, but there is no search result.

That's the result of two questions in English via ovos-cli-client:
```
wiki Elon Musk                                                                           
 >> I'm checking Wikipedia for Elon Musk
 >> That's all I can find
search wikipedia for Elon Musk
 >> I'm checking Wikipedia for Elon Musk
 >> That's all I can find
```
That's the same questions in German - in fact the same reaction as in English:
```
 wiki Elon Musk                                                                               
 >> Ich überprüfe Wikipedia für Elon Musk
 >> Mehr kann ich nicht finden
 suche wiki für Elon Musk
 >> Lass mich in Wikipedia aufschauen Elon Musk
 >> Mehr kann ich nicht finden
```
