### ISSUE TITLE
After I ask: "Tell me about elon musk" I get a response: "An error occurred while processing a request in Wikipedia Skill" 

### ISSUE THREAD

**Issue by sadpulsar** [OpenVoiceOS/skill-ovos-wikipedia#9]
After I ask: "Tell me about elon musk" I get a response: "An error occurred while processing a request in Wikipedia Skill" 

and I get this in the cli:
 18:59:23.828 - skills - mycroft.skills.mycroft_skill.mycroft_skill:_on_event_error:1131 - ERROR - [Errno Expecting value] <!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<title>Wikimedia Error</title>
<style>
* { margin: 0; padding: 0; }
body { background: #fff; font: 15px/1.6 sans-serif; color: #333; }
.content { margin: 7% auto 0; padding: 2em 1em 1em; max-width: 640px; }
.footer { clear: both; margin-top: 14%; border-top: 1px solid #e5e5e5; background: #f9f9f9; padding: 2em 0; font-size: 0.8em; text-align: center; }
img { float: left; margin: 0 2em 2em 0; }
a img { border: 0; }
h1 { margin-top: 1em; font-size: 1.2em; }
.content-text { overflow: hidden; overflow-wrap: break-word; word-wrap: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; -ms-hyphens: auto; hyphens: auto; }
p { margin: 0.7em 0 1em 0; }
a { color: #0645ad; text-decoration: none; }
a:hover { text-decoration: underline; }
code { font-family: sans-serif; }
.text-muted { color: #777; }
</style>
<div class="content" role="main">
~~~~[imedia.org](http://imedia.org/)"><img src="https://www.wikimedia.org/static/images/wmf-logo.png" srcset="https://www.wikimedia.org/static/images/wmf-logo-2x.png 2x" alt="Wikimedia" width="135" height="101">
</a>
<h1>Error</h1>
<div class="content-text">
<p>Our servers are currently under maintenance or experiencing a technical problem.

Please <a href="" title="Reload this page" onclick="window.location.reload(false); return false">try again</a> in a few&nbsp;minutes.</p>

<p>See the error message at the bottom of this page for more&nbsp;information.</p>
</div>
</div>
~~~~tream caches: cp3062 int<br>Error: 429, Too many requests - for unthrottling, contact [noc@wikimedia.org](mailto:noc@wikimedia.org) to discuss a less disruptive approach at Tue, 24 Jan 2023 18:59:23 GMT</code></p>
</div>
</html>

**Comment by JarbasAl** [comment]
please reopen if this issue persists, the skill moved from using a 3rd party lib to querying wikipedia directly so this should be fixed
